import { FileEntity } from "../FileUpload/file-entity";
import { CategoryEntity } from "../Category/category-entity";
import { UserEntity } from "../User/user-entity";
import { VendorEntity } from "../RFQVendor/vendor-entity";
import { OrganizationEntity } from "../Organization/organization-entity";
import { OrganizationUnitEntity } from "../OrganizationUnit/organization-unit-entity";
import { PurchaseRequestDetailEntity } from "../PRDetail/purchase-request-detail-entity";

export class PREntity {
  Id: string;
  Number: number;
  Description: string;
  Level: number;
  Status: string;
  RootCategoryId: string;
  FileId: string;
  BudgetOrganizationId: string;
  BudgetOrganizationUnitId: string;
  BudgetGeoId: string;
  ProjectId: string;
  ProjectBudgetId: string;
  RequestCreateDate: string;
  RequestOrganizationId: string;
  RequestOrganizationUnitId: string;
  RequestUserId: string;
  RequestPhoneNumber: string;
  ReceiptDate: string;
  ReceiveAddress: string;
  ReceiveOrganizationId: string;
  ReceiveOrganizationUnitId: string;
  ReceiveUserId: string;
  ReceivePhoneNumber: string;
  BOMApprover: string;
  FADApprover: string;
  FPDApprover: string;
  CreateDate: string;
  Comment: string;
  Instock: boolean;
  VendorId: string;
  FileEntity: FileEntity;
  RootCategoryEntity: CategoryEntity;
  RequestUserEntity: UserEntity;
  ReceiveUserEntity: UserEntity;
  BOMApproverEntity: UserEntity;
  FADApproverEntity: UserEntity;
  FPDApproverEntity: UserEntity;
  VendorEntity: VendorEntity;
  PurchasePlanEntities = null;
  RequestOrganizationEntity: OrganizationEntity;
  RequestOrganizationUnitEntity: OrganizationUnitEntity;
  ReceiveOrganizationEntity: OrganizationEntity;
  ReceiveOrganizationUnitEntity: OrganizationUnitEntity;
  BudgetOrganizationEntity: OrganizationEntity;
  BudgetOrganizationUnitEntity: OrganizationUnitEntity;
  BudgetGeographyEntity = null;
  PurchaseRequestDetailEntities : PurchaseRequestDetailEntity[];
  PurchaseRequestWorkflowEntities = null;
  MailCCEntities: UserEntity[];
  ManagerEntities: UserEntity[];
  IsEdit: boolean;
  Total: number;
  SubTotal: number;
  Note: string;
  SubRootCategoryId: string;
  SubRootCategoryEntity: CategoryEntity;
  ExpertEntities: UserEntity[];
  BudgetPeriod: string;
  ProjectEntity = null;
  ProjectBudgetEntity = null;
  TempBudgetPeriod: string;
  BudgetRemaining: number;
  FrameContract: boolean;
  QuotationDate: string;
  LinkLevel: string;
  CountPPL: number;
  IsBuyerCategory: boolean;
  RejectPRlv6: boolean;
  RejectUserEntity: UserEntity;
  BuyerId: string;
  BuyerUserEntity: UserEntity;
  CreateBy: string;
  MasterBudgetOrganizationId: string; // nut ngan s�ch l� organization b�n thanh to�n
  MasterBudgetOrganizationEntity: OrganizationEntity; // nut ngan s�ch l� organization b�n thanh to�n
  AuthorizedPaymentTotal: number;
  constructor(PurchaseRequest: any = null) {
    if (PurchaseRequest == null) {
      this.Id = null;
      this.Number = null;
      this.Description = null;
      this.Level = null;
      this.Status = null;
      this.RootCategoryId = null;
      this.FileId = null;
      this.BudgetOrganizationId = null;
      this.BudgetOrganizationUnitId = null;
      this.BudgetGeoId = null;
      this.ProjectId = null;
      this.ProjectBudgetId = null;
      this.RequestCreateDate = null;
      this.RequestOrganizationId = null;
      this.RequestOrganizationUnitId = null;
      this.RequestUserId = null;
      this.RequestPhoneNumber = null;
      this.ReceiptDate = null;
      this.ReceiveAddress = null;
      this.ReceiveOrganizationId = null;
      this.ReceiveOrganizationUnitId = null;
      this.ReceiveUserId = null;
      this.ReceivePhoneNumber = null;
      this.BOMApprover = null;
      this.FADApprover = null;
      this.FPDApprover = null;
      this.Comment = null;
      this.Instock = null;
      this.VendorId = null;
      this.FileEntity = new FileEntity();
      this.RootCategoryEntity = new CategoryEntity();
      this.RequestUserEntity = new UserEntity();
      this.ReceiveUserEntity = new UserEntity();
      this.BOMApproverEntity = new UserEntity();
      this.FADApproverEntity = new UserEntity();
      this.FPDApproverEntity = new UserEntity();
      this.VendorEntity = new VendorEntity()
      this.PurchasePlanEntities = [];
      this.RequestOrganizationEntity = new OrganizationEntity();
      this.RequestOrganizationUnitEntity = new OrganizationUnitEntity();
      this.ReceiveOrganizationEntity = new OrganizationEntity();
      this.ReceiveOrganizationUnitEntity = new OrganizationUnitEntity();
      this.BudgetOrganizationEntity = new OrganizationEntity();
      this.BudgetOrganizationUnitEntity = new OrganizationUnitEntity();
      this.BudgetGeographyEntity = null;
      this.PurchaseRequestDetailEntities = [];
      this.PurchaseRequestWorkflowEntities = [];
      this.MailCCEntities = [];
      this.ManagerEntities = [];
      this.Total = null;
      this.SubTotal = null;
      this.Note = null;
      this.SubRootCategoryId = null;
      this.SubRootCategoryEntity = new CategoryEntity();
      this.ExpertEntities = [];
      this.BudgetPeriod = null;
      this.ProjectEntity = null;
      this.ProjectBudgetEntity = null;
      this.BudgetRemaining = null;
      this.FrameContract = false;
      this.QuotationDate = null;
      this.CountPPL = null;
      this.IsBuyerCategory = null;
      this.RejectPRlv6 = null;
      this.RejectUserEntity = new UserEntity();
      this.MasterBudgetOrganizationId = null;
      this.CreateBy = null;
      this.MasterBudgetOrganizationEntity = new OrganizationEntity();
      this.BuyerId = null;
      this.BuyerUserEntity = new UserEntity();
      this.AuthorizedPaymentTotal = null;
    } else {
      this.Id = PurchaseRequest.Id;
      this.Number = PurchaseRequest.Number;
      this.Description = PurchaseRequest.Description;
      this.Level = PurchaseRequest.Level;
      this.Status = PurchaseRequest.Status;
      this.RootCategoryId = PurchaseRequest.RootCategoryId;
      this.FileId = PurchaseRequest.FileId;
      this.BudgetOrganizationId = PurchaseRequest.BudgetOrganizationId;
      this.BudgetOrganizationUnitId = PurchaseRequest.BudgetOrganizationUnitId;
      this.BudgetGeoId = PurchaseRequest.BudgetGeoId;
      this.ProjectId = PurchaseRequest.ProjectId;
      this.ProjectBudgetId = PurchaseRequest.ProjectBudgetId;
      this.CreateDate = PurchaseRequest.CreateDate;
      this.RequestCreateDate = PurchaseRequest.RequestCreateDate;
      this.RequestOrganizationId = PurchaseRequest.RequestOrganizationId;
      this.RequestOrganizationUnitId = PurchaseRequest.RequestOrganizationUnitId;
      this.RequestUserId = PurchaseRequest.RequestUserId;
      this.RequestPhoneNumber = PurchaseRequest.RequestPhoneNumber;
      this.ReceiptDate = PurchaseRequest.ReceiptDate;
      this.ReceiveAddress = PurchaseRequest.ReceiveAddress;
      this.ReceiveOrganizationId = PurchaseRequest.ReceiveOrganizationId;
      this.ReceiveOrganizationUnitId = PurchaseRequest.ReceiveOrganizationUnitId;
      this.ReceiveUserId = PurchaseRequest.ReceiveUserId;
      this.ReceivePhoneNumber = PurchaseRequest.ReceivePhoneNumber;
      this.BOMApprover = PurchaseRequest.BOMApprover;
      this.FADApprover = PurchaseRequest.FADApprover;
      this.FPDApprover = PurchaseRequest.FPDApprover;
      this.Comment = PurchaseRequest.Comment;
      this.Instock = PurchaseRequest.Instock;
      this.CreateBy = PurchaseRequest.CreateBy;
      this.FileEntity = PurchaseRequest.FileEntity;
      this.RootCategoryEntity = PurchaseRequest.RootCategoryEntity;
      this.RequestUserEntity = PurchaseRequest.RequestUserEntity != null ? PurchaseRequest.RequestUserEntity : new UserEntity();
      this.ReceiveUserEntity = PurchaseRequest.ReceiveUserEntity != null ? PurchaseRequest.ReceiveUserEntity : new UserEntity();
      this.BOMApproverEntity = PurchaseRequest.BOMApproverEntity != null ? PurchaseRequest.BOMApproverEntity : new UserEntity();
      this.FADApproverEntity = PurchaseRequest.FADApproverEntity != null ? PurchaseRequest.FADApproverEntity : new UserEntity();
      this.FPDApproverEntity = PurchaseRequest.FPDApproverEntity != null ? PurchaseRequest.FPDApproverEntity : new UserEntity();
      this.RequestOrganizationEntity = PurchaseRequest.RequestOrganizationEntity != null ? PurchaseRequest.RequestOrganizationEntity : new OrganizationEntity();
      this.RequestOrganizationUnitEntity = PurchaseRequest.RequestOrganizationUnitEntity != null ? PurchaseRequest.RequestOrganizationUnitEntity : new OrganizationUnitEntity();
      this.ReceiveOrganizationEntity = PurchaseRequest.ReceiveOrganizationEntity != null ? PurchaseRequest.ReceiveOrganizationEntity : new OrganizationEntity();
      this.ReceiveOrganizationUnitEntity = PurchaseRequest.ReceiveOrganizationUnitEntity != null ? PurchaseRequest.ReceiveOrganizationUnitEntity : new OrganizationUnitEntity();
      this.BudgetOrganizationEntity = PurchaseRequest.BudgetOrganizationEntity != null ? PurchaseRequest.BudgetOrganizationEntity : new OrganizationEntity();
      this.BudgetOrganizationUnitEntity = PurchaseRequest.BudgetOrganizationUnitEntity != null ? PurchaseRequest.BudgetOrganizationUnitEntity : new OrganizationUnitEntity();
      this.BudgetGeographyEntity = PurchaseRequest.BudgetGeographyEntity;
      this.VendorEntity = PurchaseRequest.VendorEntity != null ? PurchaseRequest.VendorEntity : new VendorEntity();
      this.VendorId = PurchaseRequest.VendorId;
      this.PurchasePlanEntities = PurchaseRequest.PurchasePlanEntities != null ? PurchaseRequest.PurchasePlanEntities : [];
      this.PurchaseRequestDetailEntities = PurchaseRequest.PurchaseRequestDetailEntities != null ? PurchaseRequest.PurchaseRequestDetailEntities : [];
      this.PurchaseRequestWorkflowEntities = PurchaseRequest.PurchaseRequestWorkflowEntities != null ? PurchaseRequest.PurchaseRequestWorkflowEntities : [];
      this.MailCCEntities = PurchaseRequest.MailCCEntities != null ? PurchaseRequest.MailCCEntities : [];
      this.ManagerEntities = PurchaseRequest.ManagerEntities
      this.Total = PurchaseRequest.Total;
      this.SubTotal = PurchaseRequest.SubTotal;
      this.Note = PurchaseRequest.Note;
      this.SubRootCategoryId = PurchaseRequest.SubRootCategoryId;
      this.SubRootCategoryEntity = PurchaseRequest.SubRootCategoryEntity;
      this.ExpertEntities = PurchaseRequest.ExpertEntities
      this.BudgetPeriod = PurchaseRequest.BudgetPeriod;
      this.ProjectEntity = PurchaseRequest.ProjectEntity 
      this.ProjectBudgetEntity = PurchaseRequest.ProjectBudgetEntity;
      this.BudgetRemaining = PurchaseRequest.BudgetRemaining;
      this.FrameContract = PurchaseRequest.FrameContract;
      this.QuotationDate = PurchaseRequest.QuotationDate;
      this.CountPPL = PurchaseRequest.CountPPL;
      this.IsBuyerCategory = PurchaseRequest.IsBuyerCategory;
      this.LinkLevel = PurchaseRequest.LinkLevel;
      this.RejectPRlv6 = PurchaseRequest.RejectPRlv6;
      this.RejectUserEntity = PurchaseRequest.RejectUserEntity != null ? PurchaseRequest.RejectUserEntity : new UserEntity();
      this.MasterBudgetOrganizationId = PurchaseRequest.MasterBudgetOrganizationId;
      this.MasterBudgetOrganizationEntity = PurchaseRequest.MasterBudgetOrganizationEntity == null ? new OrganizationEntity() : PurchaseRequest.MasterBudgetOrganizationEntity;
      this.BuyerId = PurchaseRequest.BuyerId;
      this.BuyerUserEntity = PurchaseRequest.BuyerUserEntity == null ? new UserEntity() : PurchaseRequest.BuyerUserEntity;
      this.AuthorizedPaymentTotal = PurchaseRequest.AuthorizedPaymentTotal;
    }    
  }
}
